ALTER TABLE "User" ADD COLUMN "firstName" TEXT;
ALTER TABLE "User" ADD COLUMN "lastName" TEXT;
ALTER TABLE "User" ADD COLUMN "phone" TEXT;
ALTER TABLE "User" ADD COLUMN "countryCode" TEXT;
ALTER TABLE "User" ADD COLUMN "countryName" TEXT;
ALTER TABLE "User" ADD COLUMN "city" TEXT;
ALTER TABLE "User" ADD COLUMN "region" TEXT;
ALTER TABLE "User" ADD COLUMN "ipHash" TEXT;

ALTER TABLE "Store" ADD COLUMN "countryCode" TEXT;
ALTER TABLE "Store" ADD COLUMN "countryName" TEXT;
ALTER TABLE "Store" ADD COLUMN "city" TEXT;
ALTER TABLE "Store" ADD COLUMN "region" TEXT;
