export const sellerAiConfig = {
  enabled: true,
  activationDelayMs: 10000,
  bottomSheetHeightMobile: "72%",
  maxRecommendedProducts: 3,
  leadCodePrefix: "JAK",
  whatsappIntro: "Hola, vengo de JAKAWI.",
  reserved: {
    confirmByWhatsapp: "Eso te lo confirma la tienda por WhatsApp, pero puedo ayudarte a dejar el pedido armado.",
    safeDescription: "Según la descripción del producto, puede ser una buena opción para lo que buscas.",
    maxMessages: "Para continuar mejor, escribe por WhatsApp y la tienda te confirma.",
  },
  widget: {
    closedLabel: "¿Te ayudo a elegir?",
    openedTitle: "Seller AI",
    openedSubtitle: "Te ayuda a elegir antes de escribir por WhatsApp",
    continueWhatsapp: "Continuar por WhatsApp",
    inputPlaceholder: "Escribe una respuesta corta...",
  },
  quickReplies: {
    default: ["Lo quiero para mí", "Es para regalar", "Quiero saber cómo comprar"],
    celular: ["Trabajo y redes", "Batería y cámara", "Quiero saber precio"],
    ropa: ["Algo casual", "Algo elegante", "Revisar tallas"],
    zapatos: ["Uso diario", "Para salir", "Revisar tallas"],
    maquillaje: ["Uso diario", "Para evento", "Tonos disponibles"],
    regalos: ["Es para regalar", "Tengo presupuesto", "Lo necesito pronto"],
  },
  categoryTemplates: {
    celular: "Ese modelo puede ser buena opción si buscas batería y cámara sin pagar de más. ¿Lo quieres para trabajo, estudio o redes?",
    celulares: "Ese modelo puede ser buena opción si buscas batería y cámara sin pagar de más. ¿Lo quieres para trabajo, estudio o redes?",
    tecnologia: "Ese producto encaja bien si quieres algo práctico para uso diario. ¿Lo buscas para trabajo, estudio o entretenimiento?",
    tecnologia_: "Ese producto encaja bien si quieres algo práctico para uso diario. ¿Lo buscas para trabajo, estudio o entretenimiento?",
    ropa: "Ese modelo suele quedar bien para salidas y eventos. ¿Lo buscas para algo elegante o más casual?",
    vestidos: "Ese vestido puede funcionar muy bien para una ocasión especial. ¿Lo buscas para algo elegante o más casual?",
    moda: "Ese modelo suele quedar bien para armar un look fácil. ¿Lo buscas para uso diario o para una ocasión especial?",
    zapatos: "Ese modelo combina fácil y puede servir para uso diario. ¿Quieres revisar tallas?",
    zapatillas: "Ese modelo combina fácil y puede servir para uso diario. ¿Quieres revisar tallas?",
    maquillaje: "Ese producto puede ayudarte a completar un look sin complicarte. ¿Lo buscas para diario o para un evento?",
    belleza: "Ese producto puede ayudarte a completar un look sin complicarte. ¿Lo buscas para diario o para un evento?",
    regalos: "Ese producto puede quedar bien como regalo porque es fácil de aprovechar. ¿Es para alguien especial o para ti?",
    default: "Vi que estás mirando {productName}. Te ayudo a elegir mejor: ¿lo buscas para ti o para regalar?",
  },
  intentScoreRules: {
    base: 10,
    chatOpened: 10,
    customerMessageSent: 10,
    priceQuestion: 15,
    variantQuestion: 15,
    buyIntent: 20,
    whatsappClicked: 25,
    sameProductReturn: 10,
    sameCategoryProducts: 10,
    max: 100,
  },
};
