ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "currency" TEXT DEFAULT 'BOB';
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "locale" TEXT;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "timezone" TEXT;
ALTER TABLE "Store" ALTER COLUMN "countryCode" SET DEFAULT 'BO';

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "currency" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "role" TEXT NOT NULL DEFAULT 'OWNER';
